version: '3'
services:
  app1:
    build:
      context: ./app1
    ports:
      - "7001:7001"
    networks:
      - backend

  app2:
    build:
      context: ./app2
    ports:
      - "7002:7002"
    networks:
      - backend

  frontend:
    build:
      context: ./frontend
    ports:
      - "7003:7003"
    networks:
      - backend

  nginx:
    build:
      context: ./nginx
    ports:
      - "443:443"
    depends_on:
      - app1
      - app2
      - frontend
    networks:
      - backend

networks:
  backend:
    driver: bridge
